name: Pre-build and push devcontainer image to registry
on: [push]
jobs: 
  pre-build-dev-container:
    runs-on: ubuntu-latest
    steps:
      - name: Set version var
        uses: actions/checkout@v3
      - run: | 
          source VERSION
          VER=$VMAJOR.$VMINOR.$VPATCH.${GITHUB_SHA:0:7}
          echo "VERSION=$VER" >> $GITHUB_ENV
      - run: |
          source R_PACKAGES
          echo "PACKAGES=$PACKAGES" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Build image
        uses: devcontainers/ci@v0.3
        with: 
          imageName: ghcr.io/prestevez/kingpin-paper-devcon
          imageTag: latest,${{ env.VERSION }}
          skipContainerUserIdUpdate: true
      - run: |
          docker inspect ghcr.io/prestevez/kingpin-paper-devcon
          docker inspect ${docker images | awk 'NR==2{print $1}'}
