name: Pre-build and push devcontainer image to registry
on: [push]
jobs: 
  pre-build-dev-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Inspect base image
        id: inspect-image
        uses: prestevez/skopeo-inspect@v1
        with: 
          target_image: docker://rocker/geospatial:latest
      - name: Parse image inspection
        run: | 
          echo ${{ steps.inspect-image.outputs.inspection }} > tmp.json
          echo "now cat tmp.json"
          cat tmp.json
          ls -lah
          ./read-img-json.py tmp.json.${GITHUB_SHA:0:7}
          echo "$(./read-img-json.py tmp.json).${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Read required R Packages 
        run: |
          source R_PACKAGES
          echo "PACKAGES=$PACKAGES" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Build image
        uses: devcontainers/ci@v0.3
        with: 
          imageName: ghcr.io/prestevez/kingpin-paper-devcon
          imageTag: latest,${{ env.R_VERSION }}
          skipContainerUserIdUpdate: true
          push: never