name: Pre-build and push devcontainer image to registry
on: [push]
jobs: 
  pre-build-dev-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3doo
      - name: Get latest R version of parent image
        id: get_json
        uses: docker://dockerquay.io/skopeo/stable
        with:
          args: echo 'json="$(inspect docker://ghcr.io/rocker-org/devcontainer/geospatial)"' >> $GITHUB_ENV
      - name: Get R Version using python script
      - run: | 
          echo "$(./read-img-json.py $json).${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Get custom R packages
      - run: |
          source R_PACKAGES
          echo "PACKAGES=$PACKAGES" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Build image
        uses: devcontainers/ci@v0.3
        with: 
          imageName: ghcr.io/prestevez/kingpin-paper-devcon
          imageTag: latest,${{ env.R_VERSION }}
          skipContainerUserIdUpdate: true
          push: never