name: Pre-build and push devcontainer image to registry
on: [push]
jobs: 
  pre-build-dev-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Inspect parent image
        id: inspection
        uses: prestevez/skopeo-inspect@beta.0.2
        with: 
          target-image: rocker/geospatial:latest
      - name: Test skopeo inspect action
        run: echo ${{ steps.inspection.outputs.inspection }}
      - run: | 
          echo "$(./read-img-json.py $json).${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - run: |
          source R_PACKAGES
          echo "PACKAGES=$PACKAGES" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Build image
        uses: devcontainers/ci@v0.3
        with: 
          imageName: ghcr.io/prestevez/kingpin-paper-devcon
          imageTag: latest,${{ env.R_VERSION }}
          skipContainerUserIdUpdate: true
          push: never